// app/layout.tsx
import type { Metadata } from "next";
import "../styles/calendar.scss";
import "@/styles/globals.scss";

import { AntdRegistry } from '@ant-design/nextjs-registry';
import React from 'react'; // React 임포트

export const metadata: Metadata = {
  title: "Reciplay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        {/* AntdRegistry로 children을 감싸 Ant Design 스타일을 적용 */}
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
