// app/layout.tsx
import type { Metadata } from "next";
import "../styles/globals.scss";
import "../styles/calendar.scss";

export const metadata: Metadata = {
  title: "Reciplay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
