import "@/styles/globals.scss";
import "@ant-design/v5-patch-for-react-19";
import "antd/dist/reset.css";
import "../styles/calendar.scss";

import RedirectGate from "@/components/gate/redirectGate";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import React from "react";
import SessionProviderWrapper from "../components/gate/sessionProviderWrapper";

export const metadata: Metadata = {
  title: "Reciplay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <SessionProviderWrapper>
          <RedirectGate>
            <AntdRegistry>{children}</AntdRegistry>
          </RedirectGate>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
