import { CourseCard, CourseDetail, MainCourse } from "@/types/course";

export const sampleCourse1: MainCourse[] = [
  {
    id: 2,
    title: "프랑스 제과 마스터와 함께하는 마카롱과 밀푀유",
    instructorId: 102,
    instructorName: "박파티쉐",
    thumbnail: "/images/sample2.jpg",
    category: "디저트",
    difficulty: 50,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.0,
    isLive: false,
    viewerCount: 5,
    startDate: "2025-08-11",
    endDate: "2025-09-11",
    isEnrolled: true,
  },

  {
    id: 4,
    title: "일본 가정식 마스터: 가라아게와 타마고야끼",
    instructorId: 104,
    instructorName: "스즈키 셰프",
    thumbnail: "/images/sample4.jpg",
    category: "일식",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: false,
    viewerCount: 15,
    startDate: "2025-08-13",
    endDate: "2025-09-13",
    isEnrolled: true,
  },

  {
    id: 7,
    title: "베트남 쌀국수와 분짜: 현지 스타일로 집에서 만들기",
    instructorId: 107,
    instructorName: "응우옌 선생님",
    thumbnail: "/images/sample7.jpg",
    category: "베트남 요리",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: true,
    viewerCount: 30,
    startDate: "2025-08-16",
    endDate: "2025-09-16",
    isEnrolled: false,
  },
  {
    id: 8,
    title: "스페인 타파스 마스터클래스: 감바스와 또르띠야",
    instructorId: 108,
    instructorName: "가르시아 셰프",
    thumbnail: "/images/sample1.jpg",
    category: "스페인 요리",
    difficulty: 30,
    summary: "정통 스페인 타파스 요리를 집에서 따라하는 비법을 배워보세요.",
    learningPoints: ["감바스 알 아히요", "스페인 오믈렛", "와인 페어링"],
    ratingAvg: 4.8,
    isLive: false,
    viewerCount: 42,
    startDate: "2025-08-20",
    endDate: "2025-09-20",
    isEnrolled: false,
  },
  {
    id: 9,
    title: "스페인 타파스 마스터클래스: 감바스와 또르띠야",
    instructorId: 108,
    instructorName: "가르시아 셰프",
    thumbnail: "/images/sample2.jpg",
    category: "스페인 요리",
    difficulty: 30,
    summary: "정통 스페인 타파스 요리를 집에서 따라하는 비법을 배워보세요.",
    learningPoints: ["감바스 알 아히요", "스페인 오믈렛", "와인 페어링"],
    ratingAvg: 4.8,
    isLive: true,
    viewerCount: 42,
    startDate: "2025-08-20",
    endDate: "2025-09-20",
    isEnrolled: false,
  },
  {
    id: 10,
    title: "이탈리아 파스타 마스터클래스: 볼로네제와 알리오 올리오",
    instructorId: 110,
    instructorName: "루카 셰프",
    thumbnail: "/images/sample5.jpg",
    category: "이탈리아 요리",
    difficulty: 40,
    summary: "정통 이탈리안 파스타의 기본부터 고급 소스 응용까지 배워보세요.",
    learningPoints: ["면 삶기", "소스 조합", "재료 활용법"],
    ratingAvg: 4.6,
    isLive: false,
    viewerCount: 12,
    startDate: "2025-08-21",
    endDate: "2025-09-21",
    isEnrolled: true,
  },

  {
    id: 11,
    title: "태국 요리 입문: 팟타이와 똠얌꿍",
    instructorId: 111,
    instructorName: "팟 셰프",
    thumbnail: "/images/sample4.jpg",
    category: "태국 요리",
    difficulty: 35,
    summary: "향신료와 허브를 활용한 대표적인 태국 가정식을 배워보세요.",
    learningPoints: ["팟타이 소스 만들기", "똠얌 국물 조절", "고수 다루기"],
    ratingAvg: 4.2,
    isLive: true,
    viewerCount: 22,
    startDate: "2025-08-22",
    endDate: "2025-09-22",
    isEnrolled: false,
  },

  {
    id: 12,
    title: "중식의 기초: 짜장면과 탕수육 만들기",
    instructorId: 112,
    instructorName: "장 대가",
    thumbnail: "/images/sample6.jpg",
    category: "중식",
    difficulty: 20,
    summary: "한국식 중식의 기본인 짜장면과 탕수육을 직접 만들어 봅니다.",
    learningPoints: ["춘장 볶기", "면 삶기", "튀김 반죽"],
    ratingAvg: 4.0,
    isLive: false,
    viewerCount: 8,
    startDate: "2025-08-23",
    endDate: "2025-09-23",
    isEnrolled: true,
  },

  {
    id: 13,
    title: "한식 밑반찬 완전정복: 멸치볶음부터 시금치나물까지",
    instructorId: 113,
    instructorName: "한셰프",
    thumbnail: "/images/sample2.jpg",
    category: "한식",
    difficulty: 15,
    summary: "매일 식탁에 올라오는 밑반찬을 빠르게 완성하는 노하우 공개!",
    learningPoints: ["간 맞추기", "재료 손질", "보관 팁"],
    ratingAvg: 4.5,
    isLive: false,
    viewerCount: 18,
    startDate: "2025-08-24",
    endDate: "2025-09-24",
    isEnrolled: false,
  },

  {
    id: 14,
    title: "디저트 마스터클래스: 티라미수와 브라우니",
    instructorId: 114,
    instructorName: "앨리스 베이커",
    thumbnail: "/images/sample1.jpg",
    category: "디저트",
    difficulty: 45,
    summary: "홈베이킹으로도 가능한 이탈리아식 디저트를 배워보세요.",
    learningPoints: ["마스카포네 크림", "브라우니 굽기", "플레이팅"],
    ratingAvg: 4.9,
    isLive: true,
    viewerCount: 31,
    startDate: "2025-08-25",
    endDate: "2025-09-25",
    isEnrolled: true,
  },
];
export const sampleCourse2: MainCourse[] = [
  {
    id: 8,
    title: "이탈리아 미슐랭 셰프의 프리미 피아띠 클래스",
    instructorId: 108,
    instructorName: "김밀란",
    thumbnail: "/images/sample1.jpg",
    category: "이탈리아 요리",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: true,
    viewerCount: 0,
    startDate: "2025-08-10",
    endDate: "2025-09-10",
    isEnrolled: false,
  },
  {
    id: 9,
    title: "프랑스 제과 마스터와 함께하는 마카롱과 밀푀유",
    instructorId: 109,
    instructorName: "박파티쉐",
    thumbnail: "/images/sample2.jpg",
    category: "디저트",
    difficulty: 50,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.0,
    isLive: false,
    viewerCount: 5,
    startDate: "2025-08-11",
    endDate: "2025-09-11",
    isEnrolled: true,
  },
  {
    id: 10,
    title: "기초부터 배우는 한식: 김치찌개, 불고기, 된장국",
    instructorId: 110,
    instructorName: "이한식",
    thumbnail: "/images/sample3.jpg",
    category: "한식",
    difficulty: 75,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.5,
    isLive: true,
    viewerCount: 10,
    startDate: "2025-08-12",
    endDate: "2025-09-12",
    isEnrolled: false,
  },
  {
    id: 11,
    title: "일본 가정식 마스터: 가라아게와 타마고야끼",
    instructorId: 111,
    instructorName: "스즈키 셰프",
    thumbnail: "/images/sample4.jpg",
    category: "일식",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: false,
    viewerCount: 15,
    startDate: "2025-08-13",
    endDate: "2025-09-13",
    isEnrolled: true,
  },
  {
    id: 12,
    title: "인도 커리와 탄두리 치킨 마스터클래스",
    instructorId: 112,
    instructorName: "라마 셰프",
    thumbnail: "/images/sample5.jpg",
    category: "인도 요리",
    difficulty: 50,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.0,
    isLive: true,
    viewerCount: 20,
    startDate: "2025-08-14",
    endDate: "2025-09-14",
    isEnrolled: false,
  },
  // {
  //   id: 13,
  //   title: "브런치 마스터: 오믈렛, 프렌치토스트, 아보카도토스트",
  //   instructorId: 113,
  //   instructorName: "윤브런치",
  //   thumbnail: "/images/sample6.jpg",
  //   category: "브런치",
  //   difficulty: 75,
  //   summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
  //   learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
  //   ratingAvg: 4.5,
  //   isLive: false,
  //   viewerCount: 25,
  //   startDate: "2025-08-15",
  //   endDate: "2025-09-15",
  //   isEnrolled: true,
  // },
  // {
  //   id: 14,
  //   title: "베트남 쌀국수와 분짜: 현지 스타일로 집에서 만들기",
  //   instructorId: 114,
  //   instructorName: "응우옌 선생님",
  //   thumbnail: "/images/sample7.jpg",
  //   category: "베트남 요리",
  //   difficulty: 25,
  //   summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
  //   learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
  //   ratingAvg: 3.5,
  //   isLive: true,
  //   viewerCount: 30,
  //   startDate: "2025-08-16",
  //   endDate: "2025-09-16",
  //   isEnrolled: false,
  // },
];
export const sampleCourse3: MainCourse[] = [
  {
    id: 15,
    title: "이탈리아 미슐랭 셰프의 프리미 피아띠 클래스",
    instructorId: 115,
    instructorName: "김밀란",
    thumbnail: "/images/sample1.jpg",
    category: "이탈리아 요리",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: true,
    viewerCount: 0,
    startDate: "2025-08-10",
    endDate: "2025-09-10",
    isEnrolled: false,
  },
  {
    id: 16,
    title: "프랑스 제과 마스터와 함께하는 마카롱과 밀푀유",
    instructorId: 116,
    instructorName: "박파티쉐",
    thumbnail: "/images/sample2.jpg",
    category: "디저트",
    difficulty: 50,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.0,
    isLive: false,
    viewerCount: 5,
    startDate: "2025-08-11",
    endDate: "2025-09-11",
    isEnrolled: true,
  },
  {
    id: 17,
    title: "기초부터 배우는 한식: 김치찌개, 불고기, 된장국",
    instructorId: 117,
    instructorName: "이한식",
    thumbnail: "/images/sample3.jpg",
    category: "한식",
    difficulty: 75,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.5,
    isLive: true,
    viewerCount: 10,
    startDate: "2025-08-12",
    endDate: "2025-09-12",
    isEnrolled: false,
  },
  {
    id: 18,
    title: "일본 가정식 마스터: 가라아게와 타마고야끼",
    instructorId: 118,
    instructorName: "스즈키 셰프",
    thumbnail: "/images/sample4.jpg",
    category: "일식",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: false,
    viewerCount: 15,
    startDate: "2025-08-13",
    endDate: "2025-09-13",
    isEnrolled: true,
  },
  {
    id: 19,
    title: "인도 커리와 탄두리 치킨 마스터클래스",
    instructorId: 119,
    instructorName: "라마 셰프",
    thumbnail: "/images/sample5.jpg",
    category: "인도 요리",
    difficulty: 50,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.0,
    isLive: true,
    viewerCount: 20,
    startDate: "2025-08-14",
    endDate: "2025-09-14",
    isEnrolled: false,
  },
  {
    id: 20,
    title: "브런치 마스터: 오믈렛, 프렌치토스트, 아보카도토스트",
    instructorId: 120,
    instructorName: "윤브런치",
    thumbnail: "/images/sample6.jpg",
    category: "브런치",
    difficulty: 75,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.5,
    isLive: false,
    viewerCount: 25,
    startDate: "2025-08-15",
    endDate: "2025-09-15",
    isEnrolled: true,
  },
  {
    id: 21,
    title: "베트남 쌀국수와 분짜: 현지 스타일로 집에서 만들기",
    instructorId: 121,
    instructorName: "응우옌 선생님",
    thumbnail: "/images/sample7.jpg",
    category: "베트남 요리",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: true,
    viewerCount: 30,
    startDate: "2025-08-16",
    endDate: "2025-09-16",
    isEnrolled: false,
  },
];

export const sampleCourseCards: CourseCard[] = [
  {
    specialBannerUrl: "/images/banner1.png",
    thumbnailUrl: "/images/sample1.jpg",
    viewerCount: 1250,
    title: "React 마스터 클래스",
    courseId: 1,
    category: "프론트엔드",
    averageReviewScore: 4.8,
    isLive: false,
    courseStartDate: "2025-09-01T09:00:00Z",
    courseEndDate: "2025-10-01T09:00:00Z",
    level: 2,
    summary: "React로 SPA 개발을 완벽하게 마스터합니다.",
    description:
      "기본부터 고급까지 React의 모든 기능과 최적화 기법을 학습하는 종합 강좌입니다.",
    canLearns: ["React 훅", "상태 관리", "성능 최적화", "Next.js 연동"],
    isEnrolled: true,
    announcement: "다음 주부터 새로운 섹션이 열립니다.",
    instructorId: 101,
    instructorName: "홍길동",
  },
  {
    specialBannerUrl: "/images/banner2.png",
    thumbnailUrl: "/images/sample2.jpg",
    viewerCount: 980,
    title: "Node.js 백엔드 입문",
    courseId: 2,
    category: "백엔드",
    averageReviewScore: 4.6,
    isLive: true,
    courseStartDate: "2025-08-20T12:00:00Z",
    courseEndDate: "2025-09-20T12:00:00Z",
    level: 1,
    summary: "Node.js로 서버 개발을 처음부터 배우는 과정입니다.",
    description:
      "Express를 활용한 REST API 개발과 데이터베이스 연동까지 실습합니다.",
    canLearns: ["Node.js 기본", "Express", "MongoDB", "API 설계"],
    isEnrolled: false,
    announcement: "실시간 강의가 진행 중입니다.",
    instructorId: 102,
    instructorName: "이순신",
  },
  {
    specialBannerUrl: "/images/banner3.png",
    thumbnailUrl: "/images/sample3.jpg",
    viewerCount: 2100,
    title: "파이썬 데이터 분석",
    courseId: 3,
    category: "데이터 사이언스",
    averageReviewScore: 4.9,
    isLive: false,
    courseStartDate: "2025-07-15T08:00:00Z",
    courseEndDate: "2025-08-15T08:00:00Z",
    level: 2,
    summary: "Pandas와 Matplotlib로 데이터 분석 마스터",
    description:
      "데이터 전처리, 시각화, 간단한 머신러닝 모델링까지 배우는 과정입니다.",
    canLearns: ["Pandas", "Matplotlib", "데이터 클렌징", "기초 통계"],
    isEnrolled: true,
    announcement: "추가 과제가 업로드되었습니다.",
    instructorId: 103,
    instructorName: "김영희",
  },
  {
    specialBannerUrl: "/images/banner4.png",
    thumbnailUrl: "/images/sample4.jpg",
    viewerCount: 450,
    title: "UI/UX 디자인 기초",
    courseId: 4,
    category: "디자인",
    averageReviewScore: 4.4,
    isLive: false,
    courseStartDate: "2025-10-05T10:00:00Z",
    courseEndDate: "2025-11-05T10:00:00Z",
    level: 1,
    summary: "사용자 중심 디자인의 원리를 배우는 과정",
    description: "Figma를 활용한 UI 설계와 프로토타이핑을 실습합니다.",
    canLearns: ["Figma", "디자인 원칙", "사용성 테스트", "프로토타이핑"],
    isEnrolled: false,
    announcement: "다음 수업 준비물을 확인하세요.",
    instructorId: 104,
    instructorName: "박민수",
  },
  {
    specialBannerUrl: "/images/banner5.png",
    thumbnailUrl: "/images/sample5.jpg",
    viewerCount: 3200,
    title: "Spring Boot 마이크로서비스",
    courseId: 5,
    category: "백엔드",
    averageReviewScore: 4.7,
    isLive: true,
    courseStartDate: "2025-08-10T14:00:00Z",
    courseEndDate: "2025-09-10T14:00:00Z",
    level: 3,
    summary: "Spring Boot와 Cloud를 활용한 MSA 구축",
    description:
      "Spring Boot, Spring Cloud, Docker, Kubernetes를 활용하여 마이크로서비스 아키텍처를 구현합니다.",
    canLearns: ["Spring Boot", "Spring Cloud", "Docker", "Kubernetes"],
    isEnrolled: true,
    announcement: "오늘은 라이브 Q&A 세션이 있습니다.",
    instructorId: 105,
    instructorName: "최지훈",
  },
  {
    specialBannerUrl: "/images/banner6.png",
    thumbnailUrl: "/images/sample8.jpg",
    viewerCount: 870,
    title: "Kotlin 안드로이드 앱 개발",
    courseId: 6,
    category: "모바일 개발",
    averageReviewScore: 4.5,
    isLive: false,
    courseStartDate: "2025-09-15T09:00:00Z",
    courseEndDate: "2025-10-15T09:00:00Z",
    level: 2,
    summary: "Kotlin과 Android Studio로 앱 만들기",
    description: "기초 위젯부터 네트워크 통신, 데이터베이스까지 구현합니다.",
    canLearns: ["Kotlin 기본", "안드로이드 UI", "Room DB", "API 연동"],
    isEnrolled: false,
    announcement: "다음 주 첫 실습이 진행됩니다.",
    instructorId: 106,
    instructorName: "오세훈",
  },
  {
    specialBannerUrl: "/images/banner7.png",
    thumbnailUrl: "/images/sample9.jpg",
    viewerCount: 1950,
    title: "머신러닝 입문",
    courseId: 7,
    category: "데이터 사이언스",
    averageReviewScore: 4.8,
    isLive: true,
    courseStartDate: "2025-08-25T08:00:00Z",
    courseEndDate: "2025-09-25T08:00:00Z",
    level: 1,
    summary: "Scikit-learn으로 배우는 머신러닝 기초",
    description: "분류, 회귀, 군집 알고리즘의 원리와 실습을 다룹니다.",
    canLearns: ["머신러닝 기초", "Scikit-learn", "데이터 전처리", "모델 평가"],
    isEnrolled: true,
    announcement: "오늘 라이브 코딩 세션이 있습니다.",
    instructorId: 107,
    instructorName: "정유진",
  },
  {
    specialBannerUrl: "/images/banner8.png",
    thumbnailUrl: "/images/sample10.jpg",
    viewerCount: 600,
    title: "AWS 클라우드 서비스",
    courseId: 8,
    category: "클라우드",
    averageReviewScore: 4.6,
    isLive: false,
    courseStartDate: "2025-09-10T13:00:00Z",
    courseEndDate: "2025-10-10T13:00:00Z",
    level: 2,
    summary: "AWS의 핵심 서비스와 아키텍처 설계",
    description: "EC2, S3, RDS, Lambda 등 AWS 주요 서비스를 실습합니다.",
    canLearns: ["AWS EC2", "S3", "RDS", "Lambda"],
    isEnrolled: false,
    announcement: "첫 수업 자료가 업로드되었습니다.",
    instructorId: 108,
    instructorName: "한지원",
  },
  {
    specialBannerUrl: "/images/banner9.png",
    thumbnailUrl: "/images/sample11.jpg",
    viewerCount: 1320,
    title: "Go 언어 웹 개발",
    courseId: 9,
    category: "백엔드",
    averageReviewScore: 4.4,
    isLive: false,
    courseStartDate: "2025-10-01T11:00:00Z",
    courseEndDate: "2025-11-01T11:00:00Z",
    level: 2,
    summary: "Go로 빠르고 효율적인 서버 만들기",
    description: "Gin 프레임워크로 REST API 서버를 구축합니다.",
    canLearns: ["Go 기본", "Gin", "API 설계", "동시성 처리"],
    isEnrolled: false,
    announcement: "다음 주 프로젝트 주제가 공개됩니다.",
    instructorId: 109,
    instructorName: "장민석",
  },
  {
    specialBannerUrl: "/images/banner10.png",
    thumbnailUrl: "/images/sample12.jpg",
    viewerCount: 500,
    title: "Vue 3 + TypeScript",
    courseId: 10,
    category: "프론트엔드",
    averageReviewScore: 4.7,
    isLive: true,
    courseStartDate: "2025-08-15T10:00:00Z",
    courseEndDate: "2025-09-15T10:00:00Z",
    level: 3,
    summary: "Vue 3와 TypeScript로 대규모 앱 개발",
    description: "컴포넌트 설계, Pinia 상태관리, API 연동까지 실습합니다.",
    canLearns: ["Vue 3", "TypeScript", "Pinia", "API 연동"],
    isEnrolled: true,
    announcement: "오늘 상태관리 심화 강의가 있습니다.",
    instructorId: 110,
    instructorName: "윤지훈",
  },
  {
    specialBannerUrl: "/images/banner11.png",
    thumbnailUrl: "/images/sample13.jpg",
    viewerCount: 750,
    title: "일본 요리 마스터 클래스",
    courseId: 11,
    category: "요리",
    averageReviewScore: 4.9,
    isLive: false,
    courseStartDate: "2025-09-20T09:00:00Z",
    courseEndDate: "2025-10-20T09:00:00Z",
    level: 1,
    summary: "스시부터 라멘까지 정통 일본 요리 배우기",
    description: "일본 음식 조리법과 플레이팅 비법을 전수합니다.",
    canLearns: ["스시 만들기", "라멘 육수", "튀김 기술", "플레이팅"],
    isEnrolled: false,
    announcement: "재료 준비 목록이 업로드되었습니다.",
    instructorId: 111,
    instructorName: "사토 히로시",
  },
];

export const sampleCourseDetail: CourseDetail = {
  thumbnailFileInfos: [
    {
      presignedUrl: "/images/food1.jpg",
      name: "thumb1.jpg",
      sequence: 0,
    },
  ],
  courseCoverFileInfo: {
    presignedUrl: "/images/courseDetail.png",
    name: "cover.jpg",
    sequence: 0,
  },
  title:
    "이탈리아 현지 미슐랭 요리사에게 배우는 파스타, 뇨끼, 리조또! 프리미 피아띠 정복하기",
  courseStartDate: "2025-07-23",
  courseEndDate: "2025-08-31",
  instructorId: 1,
  courseId: 101,
  enrollmentStartDate: "2025-07-01T00:00:00.000Z",
  enrollmentEndDate: "2025-07-31T23:59:59.000Z",
  category: "요리 / 양식",
  reviewCount: 350,
  averageReviewScore: 5.0,
  summary:
    "한국에서 쉽게 구할 수 있는 재료로 완성하는 양식 코스요리. 김밀란 셰프와 함께 파스타, 뇨끼, 리조또를 마스터하세요.",
  maxEnrollments: 500,
  isEnrollment: true,
  description: `안녕하세요, 유튜브 채널을 운영하며 김밀란 파스타, 리조또 2권의 책을 낸
          요리사 김밀란입니다. 이번 클래스에서는 한국에서 쉽게 구할 수 있는
          재료를 이용해 하나의 양식 코스요리를 완성해 볼 예정입니다.`,

  level: 2,
  isZzim: true,
  isLive: true,
  announcement: `강의 학습 규정:\n
- 강의 영상 공개일은 예고 없이 변경될 수 있습니다.\n
- 일부 이미지는 이해를 돕기 위한 참고 이미지입니다.\n
- 상황에 따라 조기 마감/연장될 수 있습니다.\n
- 사전 예약 강의는 공개 일정에 따라 순차적으로 오픈됩니다.`,
  isReviwed: true,
  canLearns: [
    "이탈리아 전통 파스타 제조법",
    "뇨끼 반죽과 소스 조합",
    "리조또 완성도 높이는 비법",
  ],
  lectureSummaryList: [
    {
      sequence: 1,
      lectureId: 1001,
      title: "오리엔테이션 및 재료 준비",
      startedAt: "2025-07-23T10:00:00.000Z",
      isSkipped: false,
    },
    {
      sequence: 2,
      lectureId: 1002,
      title: "파스타 만들기",
      startedAt: "2025-07-24T10:00:00.000Z",
      isSkipped: false,
    },
    {
      sequence: 3,
      lectureId: 1003,
      title: "뇨끼와1 리조또 완성",
      startedAt: "2025-07-26T10:00:00.000Z",
      isSkipped: false,
    },
    {
      sequence: 4,
      lectureId: 1003,
      title: "뇨11끼와 리조또 완성",
      startedAt: "2025-08-26T10:00:00.000Z",
      isSkipped: false,
    },
  ],
};
