import { Instructor } from "@/types/instructor";

export const sampleInstructors: Instructor[] = [
  {
    name: "김도윤",
    profileImage: "/images/김도윤.webp",
    coverImage: "/images/default-banner.png",
    introduction: "요리는 즐겁게! 실전 위주의 이탈리안 요리 전문가입니다.",
    licenses: [],
    careers: [],
    subscriberCount: 210000,
    isSubscribed: true,
  },
  {
    name: "김승민",
    profileImage: "/images/김승민.webp",
    coverImage: "/images/default-banner.png",
    introduction: "누구나 따라할 수 있는 집밥 레시피로 함께해요.",
    licenses: [],
    careers: [],
    subscriberCount: 210000,
    isSubscribed: true,
  },
  {
    name: "남정석",
    profileImage: "/images/남정석.webp",
    coverImage: "/images/default-banner.png",
    introduction: "디저트와 베이킹 전문 셰프, 감성 가득한 수업을 지향합니다.",
    licenses: [],
    careers: [],
    subscriberCount: 210000,
    isSubscribed: true,
  },
  {
    name: "박준우",
    profileImage: "/images/박준우.webp",
    coverImage: "/images/default-banner.png",
    introduction: "한식부터 분식까지! 실생활 밀착형 요리를 전합니다.",
    licenses: [],
    careers: [],
    subscriberCount: 210000,
    isSubscribed: true,
  },
  {
    name: "방기수",
    profileImage: "/images/방기수.webp",
    coverImage: "/images/default-banner.png",
    introduction: "호텔 출신 양식 셰프, 고급 레스토랑 스타일을 집으로!",
    licenses: [],
    careers: [],
    subscriberCount: 210000,
    isSubscribed: true,
  },
];
