import { Course } from "@/types/course";

export const sampleSpecialCourse: Course[] = [
  {
    id: 3,
    title: "기초부터 배우는 한식: 김치찌개, 불고기, 된장국",
    instructorId: 103,
    instructorName: "이한식",
    thumbnail: "/images/sample3.jpg",
    category: "한식",
    difficulty: 75,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.5,
    isLive: true,
    viewerCount: 10,
    startDate: "2025-08-12",
    endDate: "2025-09-12",
    isEnrolled: false,
  },
  {
    id: 4,
    title: "일본 가정식 마스터: 가라아게와 타마고야끼",
    instructorId: 104,
    instructorName: "스즈키 셰프",
    thumbnail: "/images/sample4.jpg",
    category: "일식",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: false,
    viewerCount: 15,
    startDate: "2025-08-13",
    endDate: "2025-09-13",
    isEnrolled: true,
  },
  {
    id: 5,
    title: "인도 커리와 탄두리 치킨 마스터클래스",
    instructorId: 105,
    instructorName: "라마 셰프",
    thumbnail: "/images/sample5.jpg",
    category: "인도 요리",
    difficulty: 50,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.0,
    isLive: true,
    viewerCount: 20,
    startDate: "2025-08-14",
    endDate: "2025-09-14",
    isEnrolled: false,
  },
  {
    id: 7,
    title: "베트남 쌀국수와 분짜: 현지 스타일로 집에서 만들기",
    instructorId: 107,
    instructorName: "응우옌 선생님",
    thumbnail: "/images/sample7.jpg",
    category: "베트남 요리",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: true,
    viewerCount: 30,
    startDate: "2025-08-16",
    endDate: "2025-09-16",
    isEnrolled: false,
  },
];
