import { Course } from "@/types/course";

export const sampleCourse1: Course[] = [
  {
    id: 2,
    title: "프랑스 제과 마스터와 함께하는 마카롱과 밀푀유",
    instructorId: 102,
    instructorName: "박파티쉐",
    thumbnail: "/images/sample2.jpg",
    category: "디저트",
    difficulty: 50,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.0,
    isLive: false,
    viewerCount: 5,
    startDate: "2025-08-11",
    endDate: "2025-09-11",
    isEnrolled: true,
  },

  {
    id: 4,
    title: "일본 가정식 마스터: 가라아게와 타마고야끼",
    instructorId: 104,
    instructorName: "스즈키 셰프",
    thumbnail: "/images/sample4.jpg",
    category: "일식",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: false,
    viewerCount: 15,
    startDate: "2025-08-13",
    endDate: "2025-09-13",
    isEnrolled: true,
  },

  {
    id: 7,
    title: "베트남 쌀국수와 분짜: 현지 스타일로 집에서 만들기",
    instructorId: 107,
    instructorName: "응우옌 선생님",
    thumbnail: "/images/sample7.jpg",
    category: "베트남 요리",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: true,
    viewerCount: 30,
    startDate: "2025-08-16",
    endDate: "2025-09-16",
    isEnrolled: false,
  },
  {
    id: 8,
    title: "스페인 타파스 마스터클래스: 감바스와 또르띠야",
    instructorId: 108,
    instructorName: "가르시아 셰프",
    thumbnail: "/images/sample8.jpg",
    category: "스페인 요리",
    difficulty: 30,
    summary: "정통 스페인 타파스 요리를 집에서 따라하는 비법을 배워보세요.",
    learningPoints: ["감바스 알 아히요", "스페인 오믈렛", "와인 페어링"],
    ratingAvg: 4.8,
    isLive: true,
    viewerCount: 42,
    startDate: "2025-08-20",
    endDate: "2025-09-20",
    isEnrolled: false
  },
  {
    id: 9,
    title: "스페인 타파스 마스터클래스: 감바스와 또르띠야",
    instructorId: 108,
    instructorName: "가르시아 셰프",
    thumbnail: "/images/sample8.jpg",
    category: "스페인 요리",
    difficulty: 30,
    summary: "정통 스페인 타파스 요리를 집에서 따라하는 비법을 배워보세요.",
    learningPoints: ["감바스 알 아히요", "스페인 오믈렛", "와인 페어링"],
    ratingAvg: 4.8,
    isLive: true,
    viewerCount: 42,
    startDate: "2025-08-20",
    endDate: "2025-09-20",
    isEnrolled: false
  }
];
export const sampleCourse2: Course[] = [
  {
    id: 8,
    title: "이탈리아 미슐랭 셰프의 프리미 피아띠 클래스",
    instructorId: 108,
    instructorName: "김밀란",
    thumbnail: "/images/sample1.jpg",
    category: "이탈리아 요리",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: true,
    viewerCount: 0,
    startDate: "2025-08-10",
    endDate: "2025-09-10",
    isEnrolled: false,
  },
  {
    id: 9,
    title: "프랑스 제과 마스터와 함께하는 마카롱과 밀푀유",
    instructorId: 109,
    instructorName: "박파티쉐",
    thumbnail: "/images/sample2.jpg",
    category: "디저트",
    difficulty: 50,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.0,
    isLive: false,
    viewerCount: 5,
    startDate: "2025-08-11",
    endDate: "2025-09-11",
    isEnrolled: true,
  },
  {
    id: 10,
    title: "기초부터 배우는 한식: 김치찌개, 불고기, 된장국",
    instructorId: 110,
    instructorName: "이한식",
    thumbnail: "/images/sample3.jpg",
    category: "한식",
    difficulty: 75,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.5,
    isLive: true,
    viewerCount: 10,
    startDate: "2025-08-12",
    endDate: "2025-09-12",
    isEnrolled: false,
  },
  {
    id: 11,
    title: "일본 가정식 마스터: 가라아게와 타마고야끼",
    instructorId: 111,
    instructorName: "스즈키 셰프",
    thumbnail: "/images/sample4.jpg",
    category: "일식",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: false,
    viewerCount: 15,
    startDate: "2025-08-13",
    endDate: "2025-09-13",
    isEnrolled: true,
  },
  {
    id: 12,
    title: "인도 커리와 탄두리 치킨 마스터클래스",
    instructorId: 112,
    instructorName: "라마 셰프",
    thumbnail: "/images/sample5.jpg",
    category: "인도 요리",
    difficulty: 50,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.0,
    isLive: true,
    viewerCount: 20,
    startDate: "2025-08-14",
    endDate: "2025-09-14",
    isEnrolled: false,
  },
  {
    id: 13,
    title: "브런치 마스터: 오믈렛, 프렌치토스트, 아보카도토스트",
    instructorId: 113,
    instructorName: "윤브런치",
    thumbnail: "/images/sample6.jpg",
    category: "브런치",
    difficulty: 75,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.5,
    isLive: false,
    viewerCount: 25,
    startDate: "2025-08-15",
    endDate: "2025-09-15",
    isEnrolled: true,
  },
  {
    id: 14,
    title: "베트남 쌀국수와 분짜: 현지 스타일로 집에서 만들기",
    instructorId: 114,
    instructorName: "응우옌 선생님",
    thumbnail: "/images/sample7.jpg",
    category: "베트남 요리",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: true,
    viewerCount: 30,
    startDate: "2025-08-16",
    endDate: "2025-09-16",
    isEnrolled: false,
  },
];
export const sampleCourse3: Course[] = [
  {
    id: 15,
    title: "이탈리아 미슐랭 셰프의 프리미 피아띠 클래스",
    instructorId: 115,
    instructorName: "김밀란",
    thumbnail: "/images/sample1.jpg",
    category: "이탈리아 요리",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: true,
    viewerCount: 0,
    startDate: "2025-08-10",
    endDate: "2025-09-10",
    isEnrolled: false,
  },
  {
    id: 16,
    title: "프랑스 제과 마스터와 함께하는 마카롱과 밀푀유",
    instructorId: 116,
    instructorName: "박파티쉐",
    thumbnail: "/images/sample2.jpg",
    category: "디저트",
    difficulty: 50,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.0,
    isLive: false,
    viewerCount: 5,
    startDate: "2025-08-11",
    endDate: "2025-09-11",
    isEnrolled: true,
  },
  {
    id: 17,
    title: "기초부터 배우는 한식: 김치찌개, 불고기, 된장국",
    instructorId: 117,
    instructorName: "이한식",
    thumbnail: "/images/sample3.jpg",
    category: "한식",
    difficulty: 75,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.5,
    isLive: true,
    viewerCount: 10,
    startDate: "2025-08-12",
    endDate: "2025-09-12",
    isEnrolled: false,
  },
  {
    id: 18,
    title: "일본 가정식 마스터: 가라아게와 타마고야끼",
    instructorId: 118,
    instructorName: "스즈키 셰프",
    thumbnail: "/images/sample4.jpg",
    category: "일식",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: false,
    viewerCount: 15,
    startDate: "2025-08-13",
    endDate: "2025-09-13",
    isEnrolled: true,
  },
  {
    id: 19,
    title: "인도 커리와 탄두리 치킨 마스터클래스",
    instructorId: 119,
    instructorName: "라마 셰프",
    thumbnail: "/images/sample5.jpg",
    category: "인도 요리",
    difficulty: 50,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.0,
    isLive: true,
    viewerCount: 20,
    startDate: "2025-08-14",
    endDate: "2025-09-14",
    isEnrolled: false,
  },
  {
    id: 20,
    title: "브런치 마스터: 오믈렛, 프렌치토스트, 아보카도토스트",
    instructorId: 120,
    instructorName: "윤브런치",
    thumbnail: "/images/sample6.jpg",
    category: "브런치",
    difficulty: 75,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 4.5,
    isLive: false,
    viewerCount: 25,
    startDate: "2025-08-15",
    endDate: "2025-09-15",
    isEnrolled: true,
  },
  {
    id: 21,
    title: "베트남 쌀국수와 분짜: 현지 스타일로 집에서 만들기",
    instructorId: 121,
    instructorName: "응우옌 선생님",
    thumbnail: "/images/sample7.jpg",
    category: "베트남 요리",
    difficulty: 25,
    summary: "샘플 요약 텍스트입니다. 각 요리에 대한 설명이 들어갑니다.",
    learningPoints: ["요리 기술 1", "요리 기술 2", "요리 기술 3"],
    ratingAvg: 3.5,
    isLive: true,
    viewerCount: 30,
    startDate: "2025-08-16",
    endDate: "2025-09-16",
    isEnrolled: false,
  },
];
